# Use an official OpenJDK image that matches your Java version.
# For example, for Java 21 (if available) you might use:
FROM openjdk:21-slim

# Create a volume for temporary files (used by Spring Boot)
VOLUME /tmp

# Copy the built JAR file from the target directory into the container.
# Ensure that the file name matches the one generated by your Maven build.
COPY target/democrudproject-0.0.1-SNAPSHOT.jar app.jar

# Expose the port that your Spring Boot application listens on (commonly 8080)
EXPOSE 8080

# Set the entrypoint to run the Spring Boot application.
ENTRYPOINT ["java", "-jar", "/app.jar"]